msys2: fix link error
since upgrading to gcc 6.3.0 some plugins fail to link
because of undefined reference to `osgEarth::ProfileOptions::mergeConfig(osgEarth::Config const&)'