fix glCompileShader error with placenode
Cleanup glCompileShader error:

VERTEX glCompileShader "oe_PlaceNode_icon_VS" FAILED
VERTEX Shader "oe_PlaceNode_icon_VS" infolog:
0(5) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140