Update build.md
The instructions say to install the optional dependency `webp:x64-windows` which throws the error:

```
Error: while loading web:
The port directory (C:\src\vcpkg\ports\webp) does not exist
Error: failed to load port from C:\src\vcpkg\ports\webp
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

Changing the package name to `libwebp:x64-windows` removes the error.  Was the package name changed recently?  I'm not certain that this is the correct fix, so someone in-the-know should verify that it is.