Link X11 to fix FTBFS.
 /usr/bin/ld: CMakeFiles/application_osgearth_package_qt.dir/package_qt.cpp.o: undefined reference to symbol 'XInitThreads'
 //usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

Author: Sandro Mani <manisandro@gmail.com>
Origin: https://kojipkgs.fedoraproject.org//packages/osgearth/2.6/4.fc22/src/osgearth-2.6-4.fc22.src.rpm